---
sidebar: sidebar 
permalink: alerts-start-setup.html 
keywords: bluexp, alerts, ontap, netapp 
summary: Para usar las alertas de BlueXP , realice algunos pasos para configurarlo. 
---
= Configure las alertas BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para usar las alertas de BlueXP , realice algunos pasos para configurarlo.

Antes de comenzar, revise link:alerts-start-prerequisites.html["requisitos previos"] para asegurarse de que su entorno esté listo.

Revisión https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de BlueXP"^].



== Acceso a recursos del clúster

Para ver las alertas, el usuario que ha iniciado sesión debe formar parte de la organización BlueXP  y debe tener el acceso necesario al recurso de clúster.



== Crea un conector BlueXP

Debe ponerse en contacto con su representante de ventas de NetApp para probar o utilizar este servicio. A continuación, cuando utilice el conector BlueXP , incluirá las capacidades adecuadas para el servicio de alertas.

Para crear un conector en BlueXP  antes de utilizar el servicio, consulte la documentación de BlueXP  que describe https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Cómo crear un conector BlueXP"^].

Después de configurar el conector y agregar el entorno de trabajo, espere unos 15 minutos para la detección inicial.
