---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ontap, bluexp, system manager' 
summary: Descubre las novedades de las alertas de BlueXP . 
---
= Novedades de las alertas de BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre las novedades de las alertas de BlueXP .



== 7 de octubre de 2024



=== La página de lista de alertas de BlueXP 

Usted puede identificar rápidamente clústeres de ONTAP con poca capacidad o bajo rendimiento, medir el grado de la disponibilidad e identificar los riesgos de seguridad. Es posible ver alertas relacionadas con la capacidad, el rendimiento, la protección, la disponibilidad, la seguridad y la configuración.



=== Detalles de alertas

Puede profundizar en los detalles de alertas y buscar recomendaciones.



=== Ver los detalles del clúster vinculados a ONTAP System Manager

Con las alertas de BlueXP , puede ver las alertas asociadas con su entorno de almacenamiento de ONTAP y obtener detalles vinculados a System Manager de ONTAP.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Más información sobre las alertas de BlueXP "].
